### ISSUE TITLE
automatic differentiation

### ISSUE THREAD

**Issue by jmxpearson** [jmxpearson/VinDsl.jl#2]
Need automatic differentiation for BBVI and LEG. 

See JuliaStats/Distributions.jl#430 and JuliaStats/Distributions.jl#475.
# Univariate
## Continuous
- [x] arcsine
- [x] beta
- [x] betaprime
- [x] biweight
- [x] cauchy
- [x] chi (but cf `rand`)
- [x] chisq (but cf `rand`)
- [x] cosine
- [x] epanechnikov
- [x] erlang
- [x] exponential
- [x] fdist
- [x] frechet
- [x] gamma
- [x] generalizedextremevalue (but cf `rand` and `rd`)
- [x] generalizedpareto (but cf `rand` and `rd`)
- [x] gumbel
- [x] inversegamma (stack overflow with `sqrt` of `im` \* Dual)
- [x] inversegaussian
- ~~[ ] kolmogorov~~
- ~~[ ] ksdist~~
- ~~[ ] ksonesided~~
- [x] laplace
- [x] levy (cf. note on inversegamma)
- [x] logistic
- [x] lognormal
- [x] noncentralbeta (incomplete?)
- [x] noncentralchisq
- [x] noncentralf (but cf. `rand`)
- [x] noncentralt (but cf. `rand`)
- [x] normal
- [x] normalcanon
- [x] normalinversegaussian
- [x] pareto
- [x] rayleigh
- [x] symtriangular
- [x] tdist (but `besselk` needs to be defined for `DualNumber`)
- [x] triangular
- [x] triweight
- [x] uniform
- [x] vonmises (but `besseli` needs to be defined for `DualNumber`)
- [x] weibull
## Discrete
- [x] bernoulli
- [x] betabinomial (but `special/gamma.jl` casts to Float64)
- [x] binomial
- [x] categorical
- ~~[ ] discreteuniform~~
- [x] geometric
- ~~[ ] hypergeometric~~
- [x] negativebinomial
- [x] fishernoncentralhypergeometric (but float cast in `special/gamma.jl`)
- [x] poisson
- [x] poissonbinomial (`hypot` casts to float)
- [x] skellam (`pdf` calls `bessli` only defined for float)
# Truncated
- [x] normal (on branch truncate)
  - [ ] make sure to add params for truncated distributions
  - [ ] fix method ambiguity
# Multivariate
- [x] dirichlet
- [x] multinomial
- [x] mvlognormal
- [x] mvnormal
- [x] mvnormalcanon
- [x] mvtdist
- [x] vonmisesfisher
# Matrix
- [x] inversewishart
- [x] wishart
# Mixture
- [ ] mixturemodel
- [ ] unigmm
